#!/usr/bin/env bash
export PROJECT_SOURCE
PROJECT_SOURCE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
export VERL_ROOT=${VERL_ROOT:-${PROJECT_SOURCE}/external/verl}
export PYTHONPATH=${VERL_ROOT}:${PROJECT_SOURCE}/src
export PYTHONNOUSERSITE=1 TOKENIZERS_PARALLELISM=false
export PYTHONHASHSEED=0 NCCL_CUMEM_ENABLE=0 WANDB_MODE=disabled
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-8}
export NLTK_DATA=${PROJECT_SOURCE}/nltk_data
unset ROCR_VISIBLE_DEVICES HIP_VISIBLE_DEVICES
